# Generated by Django 2.2 on 2020-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=12, unique=True)),
                ('ingamename', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('characterid', models.CharField(max_length=200, unique=True)),
                ('kperd', models.CharField(max_length=200)),
                ('yourtier', models.CharField(max_length=200)),
                ('gameserver', models.CharField(max_length=200)),
                ('winpermatches', models.CharField(max_length=200)),
                ('tpporfpp', models.CharField(max_length=200)),
                ('insquad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=100)),
            ],
        ),
    ]
