# Generated by Django 2.2 on 2020-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubglive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainform',
            name='fullname',
            field=models.CharField(max_length=12),
        ),
    ]
