# Generated by Django 2.2 on 2020-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubglive', '0002_auto_20200707_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainform',
            name='characterid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='fullname',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
